### ISSUE TITLE
error with read data

### ISSUE THREAD

**Issue by Cheng111** [chhh/deltamass#3] opened 2018-12-18 19:23 UTC
Hi, I tried to use your new version deltamass-1.0.jar/deltamass.exe. However there is a error report which is about read data. These input files worked well with the original one okde-1.5.jar. I wonder if you know the possible reasons? I run it on windows. Thank you so much.
![image](https://user-images.githubusercontent.com/16903151/50177450-0ad9a680-02d0-11e9-973a-b67c83a178a2.png)

**Comment by Cheng111** [comment] 2018-12-19 15:43
This the error report when I tried to run "java -jar deltamass-1.0.jar peaks -i ./ -f "probability>0.95" -o ./" from command line. 
![image](https://user-images.githubusercontent.com/16903151/50230531-d40c9a80-037a-11e9-90f6-66782793d5aa.png)

**Comment by chhh** [comment] 2018-12-22 21:10
The reason is the filter that you've specified. Deltamass has been completely rewritten and the custom filters have not been reimplemented properly (as I thought noone was using them).
I'll fix that. In the meantime just remove the "-f"

**Comment by Cheng111** [comment] 2019-01-02 22:13
> The reason is the filter that you've specified. Deltamass has been completely rewritten and the custom filters have not been reimplemented properly (as I thought noone was using them).
> I'll fix that. In the meantime just remove the "-f"

Hi, sorry for the late replying. I removed the "-f", but there is a new error that "PeptideProphet score could not be found in file". What the PeptideProphet score means here?  Does it mean the probability or the discriminant score. If it means the probability which is given by the peptideprophet, it is called "probability" in my file. That's why I added the "-f" to filter the data. But it looks like the software cannot find the scores. Here are the screen cut of my input file and the error report. Thank you so much.

![image](https://user-images.githubusercontent.com/16903151/50615099-28eafd80-0eb1-11e9-8571-0e4873adc4bc.png)

![image](https://user-images.githubusercontent.com/16903151/50615062-0527b780-0eb1-11e9-9ccd-df08226c5da8.png)

**Comment by pepjum** [comment] 2019-01-04 12:39
Hi, I'm having the same error parsing the file interact.pep.xml from peptideprophet.

![captura](https://user-images.githubusercontent.com/13003299/50689520-59a27280-102a-11e9-94b7-2ab9532313d0.PNG)

**Comment by chhh** [comment] 2019-01-06 07:20
@pepjum @Cheng111 
Can you please try the new version 1.1: https://github.com/chhh/deltamass/releases/tag/1.1
I don't fully understand why that happens on some systems (it doesn't on mine, so hard to debug), but this release should at least mitigate the problem.

Also, could you please send share a copy of the problematic files? (1 is enough)

**Comment by Cheng111** [comment] 2019-01-07 23:16
> @pepjum @Cheng111
> Can you please try the new version 1.1: https://github.com/chhh/deltamass/releases/tag/1.1
> I don't fully understand why that happens on some systems (it doesn't on mine, so hard to debug), but this release should at least mitigate the problem.
> 
> Also, could you please send share a copy of the problematic files? (1 is enough)

Hi, I tried the new 1.1 version, but still had the same error. I had emailed you a file. Please let me know if you didn't receive it. My system is Windows 10. Thank you so much.

**Comment by chhh** [comment] 2019-01-08 05:38
@Cheng111 Thanks, got it, will take a look

**Comment by pepjum** [comment] 2019-01-08 12:46
Hi @chhh , I also tried the new 1.1 version and the problem is the same. I must admit that I usually work in Linux and Peptideprophet and MSfragger were executed in this SO, so my input file interact.pep.xml was created on Linux and I know that this can be a problem. Do I send you a file? Maybe you have enough with the one sent by @Cheng111 to solve the problem.

Thanks for all!

**Comment by Cheng111** [comment] 2019-01-28 19:02
> @Cheng111 Thanks, got it, will take a look

Hi, I wonder if there is any update. Thank you so much.

**Comment by chhh** [comment] 2019-02-15 01:31
Sorry for the long delay, I was very busy with personal errands.
A likely fix in the new pre-release: https://github.com/chhh/deltamass/releases/tag/1.2.b03

**Comment by Cheng111** [comment] 2019-02-18 15:50
> Sorry for the long delay, I was very busy with personal errands.
> A likely fix in the new pre-release: https://github.com/chhh/deltamass/releases/tag/1.2.b03

Thank you for the update. It works for my data now.

**Comment by chhh** [comment] 2019-02-18 22:13
Fixed in [1.2.1](https://github.com/chhh/deltamass/releases/tag/1.2.1)

**Closed as completed by chhh** 2019-02-18 22:13 UTC
Labels: bug
